### ISSUE TITLE
Cannot connect to COM3D2 

### ISSUE THREAD

**Issue by Takemorikohoto** [denikson/COM3D2.MaidFiddler#15]
its literally stuck at "please wait while GUI connect to COM3D2"

**To Reproduce**
well reinstall, restart my maid fiddler but nothing work

**Expected behavior**
I have no idea. Why it happen 

**Version info (please complete the following information):**
 - Game version 1.28 
 - Maid Fiddler version [the latest one]

**Additional context**
i install the Imouto personalities without updating the game to 1.29 yet so maybe that is the problem ???

**Comment by denikson** [comment]
Greetings!

The latest personality pack requires the latest version of COM3D2.

You should also try reinstalling Maid Fiddler to make sure all the files are correctly in place.  
In addition, *you must run the game before running Maid Fiddler*. Maid Fiddler is a live editor, not a save editor; you need to have the game running in order to edit the values.

**Comment by Takemorikohoto** [comment]
well i did like you said and it still wont work

**Comment by Takemorikohoto** [comment]
ah i found the error it was the "Only one usage of each socket address (protocol/network address/port) is normally permitted". I fix it by restarting the pc a few time and it gone. But some time it just came back

**Comment by denikson** [comment]
Old issue, closing. That particular error is not related to Maid Fiddler.

Please create a new issue if the problem still persists.
