### ISSUE TITLE
what is the''please wait while GUI connect to COM3D2''

### ISSUE THREAD

**Issue by U-MT-FK** [denikson/COM3D2.MaidFiddler#24]
u mother fk:)

**Comment by denikson** [comment]
Greetings!

Please provide information about the game version and Maid Fiddler version you're using.
Since you've posted this, both game and Maid Fiddler were updated.

Generally, the message means that Maid Fiddler is waiting for your game to launch so it connect to it.

If you have any issues, please create a new issue and follow the provided template.
