### ISSUE TITLE
GUI refuses to connect even with the game opened.

### ISSUE THREAD

**Issue by jdramirez165** [denikson/COM3D2.MaidFiddler#28]
Yeah i have no idea whats happening. I swear the game is open but the GUI still can't connect. Even restarting the game & the GUI, its the same thing. Whats happening? Please fix this ASAP.

**Comment by muudzi** [comment]
I have the same problem, it seems that `MaidStatus.Feeling` is not loaded and causes an infinite wait
![Screenshot (41)](https://user-images.githubusercontent.com/32554295/75820201-35603400-5d9c-11ea-9969-4e0142ee7450.png)

**Comment by muudzi** [comment]
Updating to 1.45.0 fixed it for me, I was on 1.44.
Here are the instructions to update the game:
https://wiki.anime-sharing.com/hgames/index.php?title=Custom_Order_Maid_3D_2/Technical_Help#Updating_the_game_.28Japanese_version.29

**Comment by denikson** [comment]
Greetings!

Please provide more info: what game version are you running, what Maid Fiddler version? Any errors in the console?

As it is, the Maid Fiddler 1.0.7.0 is known to work with COM 1.45 (JP) and 1.04.2 (ENG).

Closing this issue because of insufficient information. Please create a new issue using the proper template.
